id: PE44ABAC0
initial_creation_type: input
source_metadata:
  title: Offering Series
  language: de
  description: 'Lotsawa House presents the following texts related to the practice
    of offering (mchod pa):'
  volume:
    2f7d830dfb4c4d5b81cb143536e6a9ae:
      title: Offering the Eight Auspicious Substances and Seven Emblems of Royalty
      parent: Eight Auspicious Substances
    80470ad149a646bf94e73d11df556dd2:
      title: Teaching on the Offering of Flowers
      parent: Flower Offering
    6628ebc01b444fabab6908704776ffd4:
      title: 'The Offering Clouds of the Indestructible Ladies of Sound: Concise Garland
        of Offerings of the Sixteen Vajra Goddesses'
      parent: Garland of Offerings
    1e480aea2ef241919cca049eec80acbe:
      title: Offering to the Nāgas of Gangtok
      parent: Offering to Nāgas
    6430c49cd78845c6a7f8b599cb4d22fd:
      title: Töpa Gyatsoma Offering Prayer
      parent: Prayers
    379e297b22254b838923483fa75e357a:
      title: 'The Wish-Granting King of Jewels: An Essential Garland of Offerings'
      parent: Prayers
    10dae583118c4d9aad5a144220974ceb:
      title: Great Clouds of First-Portion Offerings for Prosperity
      parent: Prosperity
    9d7eec75b2ea4c40b17c1af72896d868:
      title: White and Red Sur Offerings That Are Very Easy to Apply
      parent: Sur Offering
    8805755676e845ac9642c2255a9a8dbe:
      title: Brief Red Sur Offering
      parent: Sur Offering
    ad41211fe73e4a7b86efd985b9c78b75:
      title: Brief Sur Offering
      parent: Sur Offering
    72dc4213f9704c498cf574e4d95f356c:
      title: A Means of Offering Sur to the Damsi, Gyalgong and Others
      parent: Sur Offering
    d2d2ae8f43cd483bae54f287c1e48d4f:
      title: 'Freedom from All Adversity: A Sur Offering to Harmful Influences, Obstacle-Makers
        and Elemental Spirits'
      parent: Sur Offering
    15bf8cec2aeb4aa29b3ba8a62ac28e39:
      title: The Verse for Offering Water from the Pure Vision, An Ocean of Accomplishments
      parent: Water Offering
created_at: '2022-03-01T05:00:22.321929'
last_modified_at: '2022-03-01T05:00:22.321931'
